server:
  context-path: /exercice
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/primefacesexo
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
